openapi: 3.0.1
info:
  contact:
    email: help@accentvoice.io
    name: Accent Team
    url: https://accentvoice.io/
  description: Initialize Accent Engine from a REST API
  title: accent-setupd
  version: 1.0.0
  x-logo:
    altText: Accent Logo
    backgroundColor: '#FAFAFA'
    url: https://accentvoice.io/images/logo-black.svg
servers:
- url: http://api.accentvoice.io/1.0
- url: https://api.accentvoice.io/1.0
security:
- accent_auth_token: []
paths:
  /config:
    get:
      description: '**Required ACL:** `setupd.config.read`'
      operationId: getConfig
      responses:
        "200":
          content: {}
          description: The configuration of the service
      summary: Show the current configuration
      tags:
      - config
  /setup:
    post:
      operationId: create
      requestBody:
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/SetupRequest'
        description: Setup options
        required: true
      responses:
        "201":
          content: {}
          description: The setup has been completed
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Invalid request
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: A error occurred during the setup
        "503":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: "Another service is unavailable (e.g. accent-auth, accent-confd,\
            \ Asterisk, ...)"
      summary: Setup the Accent Engine
      tags:
      - setup
      x-codegen-request-body-name: body
  /status:
    get:
      description: '**Required ACL:** `setupd.status.read`'
      operationId: getStatus
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusSummary'
          description: The internal infos of accent-setupd
      summary: Print infos about internal status of accent-setupd
      tags:
      - status
components:
  parameters:
    TokenID:
      description: The token's ID
      in: query
      name: token
      schema:
        type: string
  requestBodies:
    SetupBody:
      content:
        '*/*':
          schema:
            $ref: '#/components/schemas/SetupRequest'
      description: Setup options
      required: true
  responses:
    AnotherServiceUnavailable:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: "Another service is unavailable (e.g. accent-auth, accent-confd,\
        \ Asterisk, ...)"
    InvalidRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: Invalid request
    NotFoundError:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: The resource requested was not found on the server
    SetupError:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      description: A error occurred during the setup
  schemas:
    ComponentWithStatus:
      example:
        status: null
      properties:
        status:
          $ref: '#/components/schemas/StatusValue'
      type: object
    Error:
      description: Error message for the client
      example:
        error_id: error_id
        details: "{}"
        message: message
        timestamp: 0.8008281904610115
      properties:
        details:
          description: Additional information about the error. The keys are specific
            to each error.
          properties: {}
          type: object
        error_id:
          description: Identifier of the type of error. It is more precise than the
            HTTP status code.
          type: string
        message:
          description: Human readable explanation of the error
          type: string
        timestamp:
          description: Time when the error occured
          format: timestamp
          type: number
      title: Error
      type: object
    SetupRequest:
      example:
        engine_rtp_stunaddr: "null"
        nestbox_service_id: nestbox_service_id
        engine_license: true
        nestbox_port: 6
        engine_password: engine_password
        engine_rtp_icesupport: false
        engine_internal_address: engine_internal_address
        nestbox_service_key: nestbox_service_key
        nestbox_engine_host: nestbox_engine_host
        nestbox_instance_name: nestbox_instance_name
        nestbox_host: nestbox_host
        nestbox_verify_certificate: true
        engine_instance_uuid: engine_instance_uuid
        engine_language: engine_language
        nestbox_engine_port: 0
      properties:
        engine_instance_uuid:
          description: 'The UUID identifying this instance on Nestbox. The engine_instance_uuid
            should only be specified if the instance has already been registered on
            the specified Nestbox. Omitting this field for an instance that is already
            registered will create a duplicate entry on the Nestbox. '
          type: string
        engine_internal_address:
          description: IP address of the engine
          type: string
        engine_language:
          description: The interface language for the Accent Engine (either `en_US`
            or `fr_FR`)
          type: string
        engine_license:
          description: Whether the GNU GPLv3 license is accepted
          type: boolean
        engine_password:
          description: Password of the first administrator ``root`` on the engine
          type: string
        engine_rtp_icesupport:
          default: false
          description: 'Enable ICE support. This is required for WebRTC. A STUN server
            must be defined in the `engine_rtp_stunaddr` field when using `engine_rtp_icesupport=true`. '
          type: boolean
        engine_rtp_stunaddr:
          default: "null"
          description: The address of the STUN server to use for WebRTC
          type: string
        nestbox_engine_host:
          description: Host used by Nestbox to contact the engine
          type: string
        nestbox_engine_port:
          description: Port used by Nestbox to contact the engine
          type: integer
        nestbox_host:
          description: Host of the Nestbox where the engine will register. Specifying
            this key will make nestbox and `engine_internal_address` keys mandatory.
            Accent will be connected to the specified Nestbox instance.
          type: string
        nestbox_instance_name:
          description: Name of the engine in Nestbox
          type: string
        nestbox_port:
          description: Port of the Nestbox where the engine will register
          type: integer
        nestbox_service_id:
          description: Nestbox username used to register the engine
          type: string
        nestbox_service_key:
          description: Nestbox password used to register the engine
          type: string
        nestbox_verify_certificate:
          default: true
          description: Should the certificate used for HTTPS be verified? The setup
            will abort if the certificate fails the verification.
          type: boolean
      required:
      - engine_language
      - engine_license
      - engine_password
      type: object
    StatusSummary:
      example:
        master_tenant:
          status: null
        rest_api:
          status: null
      properties:
        master_tenant:
          $ref: '#/components/schemas/ComponentWithStatus'
        rest_api:
          $ref: '#/components/schemas/ComponentWithStatus'
      type: object
    StatusValue:
      enum:
      - fail
      - ok
      type: string
  securitySchemes:
    accent_auth_token:
      in: header
      name: X-Auth-Token
      type: apiKey
x-accent-name: setupd
x-accent-port: 9302
x-original-swagger-version: "2.0"
